### ISSUE TITLE
SQLite 'iosDatabaseLocation' does not exist error when transpile Ionic 2 apps

### ISSUE THREAD

**Issue by Gengjun-VVU** [nolanlawson/pouchdb-adapter-cordova-sqlite#38]
Hi Nolan,

I am testing PouchDB SQLite plugins recently, as I need it for my app to store data permanently on device.

I followed the instruction to install the following plugins:
1. Cordova-sqlite-storage
2. cordova-plugin-sqlite-2
3. pouchdb-adapter-cordova-sqlite

My code for creating a database is:
```
initDB() {
    var PouchAdapterCordovaSqlite = require('pouchdb-adapter-cordova-sqlite');
    PouchDB.plugin(PouchAdapterCordovaSqlite);
    this._db = new PouchDB('birthday', {
        adapter: 'cordova-sqlite',
        iosDatabaseLocation: 'Library'
      });
    this._db.info().then(console.log.bind(console));
    let alert = this.alertCtrl.create({
      title: 'Local Storage Database',
      message: 'The adapter is: ' + this._db.adapter,
      buttons: ['Ok']
    });
    alert.present();
  }
``` 
Then I got the following error when transpile the app with webpack:
```
[20:11:33]  typescript: src/providers/birthday-service.ts, line: 29 
Argument of type '{ adapter: string; iosDatabaseLocation: string; }' is not assignable
to parameter of type 'DatabaseConfiguration'. Object literal may only specify known
properties, and 'iosDatabaseLocation' does not exist in type 'DatabaseConfiguration'. 

L28:    adapter: 'cordova-sqlite',
L29:    iosDatabaseLocation: 'Library'
L30:  });
```
After checking the docs for Cordova-sqlite-storage, I have changed:
`iosDatabaseLocation: 'Library'`
to
`location: 'default'`
but the error is still the same. It looks like the somehow the PouchDB does not use cordova SQLite storage due to the property does not exist as shown in the error message.

Could you please help me to configure the PouchDB correctly so that it actually uses SQLite? Thank you for your help. Much appreciated!

GJ Wu

**Comment by nolanlawson** [comment]
This appears to be a TypeScript issue. Most likely the TypeScript definitions are not accurate. You should be able to apply your own custom TS definitions or update https://github.com/DefinitelyTyped/DefinitelyTyped

Also you should know that iosDatabaseLocation is not required for cordova-plugin-sqlite-2. I intentionally differed from Cordova-sqlite-storage because I thought it would be simpler to have no configuration for the location. Also you don't need to install both Cordova-sqlite-storage and cordova-plugin-sqlite-2 because they are competitors; they both do the same thing.

Hope that helps!
